# Generated by Django 4.1.4 on 2022-12-23 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shamba', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
